// ignore_for_file: avoid_print
import 'dart:io';

void main() {
  final dir = Directory('SYLLABUSES');
  if (!dir.existsSync()) {
    print('Error: SYLLABUSES directory not found in the root directory.');
    exit(1);
  }

  final files = dir
      .listSync()
      .where((f) => f is File && f.path.endsWith('_SYLLABUS.md'))
      .cast<File>()
      .toList();

  if (files.isEmpty) {
    print('Error: No *_SYLLABUS.md files found in SYLLABUSES/ directory.');
    exit(1);
  }

  // Sort files to guarantee deterministic generation output
  files.sort((a, b) => a.path.compareTo(b.path));

  // Let's define the neon colors
  final colors = [
    0xFFFF0000, // Neon Red
    0xFF39FF14, // Neon Green
    0xFF00F0FF, // Neon Cyan
    0xFFD500F9, // Neon Purple
    0xFFFFE500, // Neon Yellow
    0xFFFF6C00, // Neon Orange
    0xFFFF1493, // Deep Pink
    0xFF2979FF, // Vibrant Blue
  ];

  final buffer = StringBuffer();
  buffer.writeln('// GENERATED FILE - DO NOT EDIT MANUALLY');
  buffer.writeln('// Generated by parse_syllabus.dart');
  buffer.writeln();
  buffer.writeln('class PresetCategory {');
  buffer.writeln('  final String name;');
  buffer.writeln('  final int color;');
  buffer.writeln('  final List<PresetTopic> topics;');
  buffer.writeln();
  buffer.writeln('  const PresetCategory({');
  buffer.writeln('    required this.name,');
  buffer.writeln('    required this.color,');
  buffer.writeln('    required this.topics,');
  buffer.writeln('  });');
  buffer.writeln('}');
  buffer.writeln();
  buffer.writeln('class PresetTopic {');
  buffer.writeln('  final String name;');
  buffer.writeln('  final List<String> tasks;');
  buffer.writeln();
  buffer.writeln('  const PresetTopic({');
  buffer.writeln('    required this.name,');
  buffer.writeln('    required this.tasks,');
  buffer.writeln('  });');
  buffer.writeln('}');
  buffer.writeln();

  final branchKeys = <String>[];

  for (final file in files) {
    final filename = file.uri.pathSegments.last;
    final branchName = filename.split('_').first.toUpperCase();
    branchKeys.add(branchName);

    print('Parsing $filename for branch $branchName...');
    final lines = file.readAsLinesSync();

    final categories = <Map<String, dynamic>>[];
    Map<String, dynamic>? currentCategory;
    Map<String, dynamic>? currentTopic;

    int colorIdx = 0;

    for (var line in lines) {
      line = line.trim();
      if (line.startsWith('## ')) {
        // Category
        var name = line.substring(3).trim();
        // Remove any prefix number like "1. " or "10. "
        final numReg = RegExp(r'^\d+\.\s+');
        name = name.replaceFirst(numReg, '');

        final color = colors[colorIdx % colors.length];
        colorIdx++;

        currentCategory = {
          'name': name,
          'color': color,
          'topics': <Map<String, dynamic>>[],
        };
        categories.add(currentCategory);
        currentTopic = null;
      } else if (line.startsWith('### ')) {
        // Topic
        if (currentCategory == null) continue;
        final name = line.substring(4).trim();
        currentTopic = {
          'name': name,
          'tasks': <String>[],
        };
        (currentCategory['topics'] as List<Map<String, dynamic>>).add(currentTopic);
      } else if (line.startsWith('* [ ]') || line.startsWith('* [x]')) {
        // Task
        if (currentTopic == null) continue;
        final name = line.substring(5).trim();
        if (name.isNotEmpty) {
          (currentTopic['tasks'] as List<String>).add(name);
        }
      }
    }

    // Write individual list for this branch
    buffer.writeln('const List<PresetCategory> ${branchName.toLowerCase()}Presets = [');
    for (final cat in categories) {
      buffer.writeln('  PresetCategory(');
      buffer.writeln('    name: ${escapeString(cat['name'] as String)},');
      buffer.writeln('    color: 0x${(cat['color'] as int).toRadixString(16).toUpperCase()},');
      buffer.writeln('    topics: [');
      for (final topic in cat['topics'] as List<Map<String, dynamic>>) {
        buffer.writeln('      PresetTopic(');
        buffer.writeln('        name: ${escapeString(topic['name'] as String)},');
        buffer.writeln('        tasks: [');
        for (final task in topic['tasks'] as List<String>) {
          buffer.writeln('          ${escapeString(task)},');
        }
        buffer.writeln('        ],');
        buffer.writeln('      ),');
      }
      buffer.writeln('    ],');
      buffer.writeln('  ),');
    }
    buffer.writeln('];');
    buffer.writeln();
  }

  // Generate the central map mapping branch key to its presets list
  buffer.writeln('const Map<String, List<PresetCategory>> branchPresets = {');
  for (final branch in branchKeys) {
    buffer.writeln('  \'$branch\': ${branch.toLowerCase()}Presets,');
  }
  buffer.writeln('};');
  buffer.writeln();

  // Backward compatibility alias (default to CS)
  buffer.writeln('const List<PresetCategory> defaultSyllabusPreset = csPresets;');

  final outputFile = File('lib/database/syllabus_preset.dart');
  outputFile.writeAsStringSync(buffer.toString());
  print('Successfully parsed and generated lib/database/syllabus_preset.dart with branches: ${branchKeys.join(", ")}');
}

String escapeString(String s) {
  final escaped = s
      .replaceAll('\\', '\\\\')
      .replaceAll('\'', '\\\'')
      .replaceAll('\$', '\\\$')
      .replaceAll('\n', '\\n');
  return "'$escaped'";
}
