import 'dart:io';

void main() {
  final file = File('SYLLABUS.md');
  if (!file.existsSync()) {
    print('Error: SYLLABUS.md not found in the root directory.');
    exit(1);
  }

  final lines = file.readAsLinesSync();

  final categories = <Map<String, dynamic>>[];
  Map<String, dynamic>? currentCategory;
  Map<String, dynamic>? currentTopic;

  // Let's define the neon colors
  final colors = [
    0xFFFF073A, // Neon Red
    0xFF39FF14, // Neon Green
    0xFF00F0FF, // Neon Cyan
    0xFFD500F9, // Neon Purple
    0xFFFFE500, // Neon Yellow
    0xFFFF6C00, // Neon Orange
    0xFFFF1493, // Deep Pink
    0xFF2979FF, // Vibrant Blue
  ];

  int colorIdx = 0;

  for (var line in lines) {
    line = line.trim();
    if (line.startsWith('## ')) {
      // Category
      var name = line.substring(3).trim();
      // Remove any prefix number like "1. "
      final numReg = RegExp(r'^\d+\.\s+');
      name = name.replaceFirst(numReg, '');

      final color = colors[colorIdx % colors.length];
      colorIdx++;

      currentCategory = {
        'name': name,
        'color': color,
        'topics': <Map<String, dynamic>>[],
      };
      categories.add(currentCategory);
      currentTopic = null;
    } else if (line.startsWith('### ')) {
      // Topic
      if (currentCategory == null) continue;
      final name = line.substring(4).trim();
      currentTopic = {
        'name': name,
        'tasks': <String>[],
      };
      (currentCategory['topics'] as List<Map<String, dynamic>>).add(currentTopic);
    } else if (line.startsWith('* [ ]') || line.startsWith('* [x]')) {
      // Task
      if (currentTopic == null) continue;
      final name = line.substring(5).trim();
      if (name.isNotEmpty) {
        (currentTopic['tasks'] as List<String>).add(name);
      }
    }
  }

  // Let's write the generated file to lib/database/syllabus_preset.dart
  final buffer = StringBuffer();
  buffer.writeln('// GENERATED FILE - DO NOT EDIT MANUALLY');
  buffer.writeln('// Generated by parse_syllabus.dart');
  buffer.writeln();
  buffer.writeln('class PresetCategory {');
  buffer.writeln('  final String name;');
  buffer.writeln('  final int color;');
  buffer.writeln('  final List<PresetTopic> topics;');
  buffer.writeln();
  buffer.writeln('  const PresetCategory({');
  buffer.writeln('    required this.name,');
  buffer.writeln('    required this.color,');
  buffer.writeln('    required this.topics,');
  buffer.writeln('  });');
  buffer.writeln('}');
  buffer.writeln();
  buffer.writeln('class PresetTopic {');
  buffer.writeln('  final String name;');
  buffer.writeln('  final List<String> tasks;');
  buffer.writeln();
  buffer.writeln('  const PresetTopic({');
  buffer.writeln('    required this.name,');
  buffer.writeln('    required this.tasks,');
  buffer.writeln('  });');
  buffer.writeln('}');
  buffer.writeln();
  buffer.writeln('const List<PresetCategory> defaultSyllabusPreset = [');

  for (final cat in categories) {
    buffer.writeln('  PresetCategory(');
    buffer.writeln('    name: ${escapeString(cat['name'] as String)},');
    buffer.writeln('    color: 0x${(cat['color'] as int).toRadixString(16).toUpperCase()},');
    buffer.writeln('    topics: [');
    for (final topic in cat['topics'] as List<Map<String, dynamic>>) {
      buffer.writeln('      PresetTopic(');
      buffer.writeln('        name: ${escapeString(topic['name'] as String)},');
      buffer.writeln('        tasks: [');
      for (final task in topic['tasks'] as List<String>) {
        buffer.writeln('          ${escapeString(task)},');
      }
      buffer.writeln('        ],');
      buffer.writeln('      ),');
    }
    buffer.writeln('    ],');
    buffer.writeln('  ),');
  }

  buffer.writeln('];');

  final outputFile = File('lib/database/syllabus_preset.dart');
  outputFile.writeAsStringSync(buffer.toString());
  print('Successfully parsed and generated lib/database/syllabus_preset.dart');
}

String escapeString(String s) {
  final escaped = s
      .replaceAll('\\', '\\\\')
      .replaceAll('\'', '\\\'')
      .replaceAll('\$', '\\\$')
      .replaceAll('\n', '\\n');
  return "'$escaped'";
}
