// GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by parse_syllabus.dart

class PresetCategory {
  final String name;
  final int color;
  final List<PresetTopic> topics;

  const PresetCategory({
    required this.name,
    required this.color,
    required this.topics,
  });
}

class PresetTopic {
  final String name;
  final List<String> tasks;

  const PresetTopic({
    required this.name,
    required this.tasks,
  });
}

const List<PresetCategory> defaultSyllabusPreset = [
  PresetCategory(
    name: 'Mathematics',
    color: 0xFFFF073A,
    topics: [
      PresetTopic(
        name: 'Discrete Mathematics',
        tasks: [
          'Propositional logic truth tables and connectives',
          'Tautologies, contradictions, and contingency verification',
          'First-order logic predicates and quantifiers',
          'Logical validity and inference rules',
          'Set operations, laws, power sets, and cardinality',
          'Principle of Inclusion-Exclusion for sets',
          'Equivalence relations and equivalence classes',
          'Reflexive, symmetric, and transitive closures of relations',
          'Properties of functions (Injective, Surjective, Bijective)',
          'Composition of functions and inverse functions',
          'Partial orders, Posets, and Hasse diagrams',
          'Lattices, bounded lattices, distributive lattices, and complemented lattices',
          'Monoids definition and algebraic properties',
          'Groups, subgroups, and Lagrange\'s theorem',
          'Graph connectivity, paths, cycles, and components',
          'Eulerian graphs and Hamiltonian graphs properties',
          'Graph matching and Hall\'s Marriage Theorem',
          'Graph colouring and Chromatic number calculation',
          'Planar graphs and Euler\'s formula',
          'Permutations and combinations counting techniques',
          'Pigeonhole principle applications',
          'Linear homogeneous recurrence relations solving',
          'Linear non-homogeneous recurrence relations solving',
          'Ordinary generating functions formulation and execution',
        ],
      ),
      PresetTopic(
        name: 'Linear Algebra',
        tasks: [
          'Matrix properties, types, and determinants',
          'Rank of a matrix calculation',
          'Inverse and trace of a matrix',
          'Systems of linear equations consistency verification',
          'Gaussian elimination execution',
          'Eigenvalues and eigenvectors computation',
          'Cayley-Hamilton theorem applications',
          'LU decomposition factorization',
        ],
      ),
      PresetTopic(
        name: 'Calculus',
        tasks: [
          'Limits evaluation and L\'Hopital\'s rule',
          'Continuity verification of single variable functions',
          'Differentiability verification of single variable functions',
          'Maxima and minima local and global optimization',
          'Rolle\'s and Lagrange\'s Mean Value Theorems',
          'Definite and indefinite integration execution',
        ],
      ),
      PresetTopic(
        name: 'Probability and Statistics',
        tasks: [
          'Conditional probability calculation',
          'Bayes theorem application',
          'Discrete random variables, PMF, and CDF',
          'Continuous random variables, PDF, and CDF',
          'Uniform distribution properties (Discrete and Continuous)',
          'Normal distribution properties and Z-score calculations',
          'Exponential distribution and memoryless property',
          'Poisson distribution calculation',
          'Binomial distribution calculation',
          'Mean, median, and mode calculation',
          'Variance and standard deviation calculation',
        ],
      ),
    ],
  ),
  PresetCategory(
    name: 'Digital Logic',
    color: 0xFF39FF14,
    topics: [
      PresetTopic(
        name: 'Boolean Algebra & Minimization',
        tasks: [
          'Boolean algebra laws, simplification, and duality theorems',
          'Karnaugh maps minimization (up to 5 variables)',
          'Implicants, prime implicants, and essential prime implicants extraction',
          'Logic gate implementations using universal gates (NAND and NOR)',
        ],
      ),
      PresetTopic(
        name: 'Combinational Circuits',
        tasks: [
          'Half adder and full adder design',
          'Half subtractor and full subtractor design',
          'Ripple carry and look-ahead carry adders',
          'Multiplexers implementation and Boolean function minimization via MUX',
          'Demultiplexers and decoders execution',
          'Encoders and priority encoders design',
          'Code converters configuration (Binary, Gray, BCD)',
        ],
      ),
      PresetTopic(
        name: 'Sequential Circuits',
        tasks: [
          'SR, JK, D, and T latch implementations',
          'Flip-flop excitation tables and conversions',
          'Race-around condition and Master-Slave JK flip-flop mechanics',
          'Shift registers and universal shift registers design',
          'Asynchronous (ripple) counters analysis and design',
          'Synchronous counters analysis and design',
          'Ring counters and Johnson counters execution',
        ],
      ),
      PresetTopic(
        name: 'Number Representations & Computer Arithmetic',
        tasks: [
          'Number base systems conversions (Binary, Octal, Decimal, Hexadecimal)',
          'Signed magnitude and 1\'s complement representation',
          '2\'s complement representation and arithmetic',
          'Fixed-point arithmetic addition, subtraction, and overflow conditions',
          'IEEE 754 single precision floating-point format representation',
          'IEEE 754 double precision floating-point format representation',
        ],
      ),
    ],
  ),
  PresetCategory(
    name: 'COA',
    color: 0xFF00F0FF,
    topics: [
      PresetTopic(
        name: 'Machine Instructions & Addressing Modes',
        tasks: [
          'Instruction cycle phases parsing',
          'Immediate, direct, and indirect addressing modes execution',
          'Register and register indirect addressing modes execution',
          'Indexed, base-register, and relative addressing modes execution',
          'Zero, one, two, and three-address instruction formats parsing',
        ],
      ),
      PresetTopic(
        name: 'CPU Control & Datapath Design',
        tasks: [
          'ALU operational datapath configuration',
          'Single-bus and multi-bus CPU datapath organizations',
          'Hardwired control unit architecture execution',
          'Microprogrammed control unit microinstructions implementation',
        ],
      ),
      PresetTopic(
        name: 'Instruction Pipelining',
        tasks: [
          'Pipelining execution stages, clock cycle time, and throughput calculations',
          'Pipeline speedup, efficiency, and CPI calculations',
          'Structural hazards identification and mitigation',
          'Data hazards identification and operand forwarding solutions (RAW, WAR, WAW)',
          'Control hazards, branch delays, penalties, and branch prediction methods',
        ],
      ),
      PresetTopic(
        name: 'Memory Hierarchy',
        tasks: [
          'Cache direct mapping trace and address partition',
          'Cache fully associative mapping trace and address partition',
          'Cache set-associative mapping trace and address partition',
          'Cache write policies execution (Write-through, Write-back, Write-allocate)',
          'Cache replacement algorithms tracing (LRU, FIFO, Optimal)',
          'Main memory DRAM, SRAM, and interleaved configurations',
          'Secondary storage disk performance metrics (Seek time, Rotational latency, Transfer time)',
          'Translation Lookaside Buffer (TLB) hit and miss tracking',
          'Virtual memory address translation and page fault calculations',
        ],
      ),
      PresetTopic(
        name: 'I/O Interface',
        tasks: [
          'Programmed I/O transfer tracking',
          'Interrupt-driven I/O processing and priority structures (Daisy chaining)',
          'DMA (Direct Memory Access) cycle stealing and burst mode transfers',
        ],
      ),
    ],
  ),
  PresetCategory(
    name: 'Programming in C',
    color: 0xFFD500F9,
    topics: [
      PresetTopic(
        name: 'C Language Fundamentals',
        tasks: [
          'Tokens, data types, and operators execution',
          'Expression evaluation precedence and associativity parsing',
          'Conditional statement branching execution (if-else, switch-case)',
          'Iterative loop execution (for, while, do-while, break, continue)',
          'Function call parameter passing (Call by value)',
          'Function call parameter passing (Call by reference using pointers)',
          'Storage classes tracing (auto, register, static, extern)',
        ],
      ),
      PresetTopic(
        name: 'Advanced Data Types & Memory Access',
        tasks: [
          'Recursion tracing, base conditions, and runtime stack analysis',
          '1D array indexing and memory mapping',
          '2D and multi-dimensional array row-major and column-major memory mapping',
          'Pointer arithmetic and multi-level pointers dereferencing',
          'Pointers to functions and arrays of pointers tracking',
          'Structures and unions memory offset allocation and padding calculation',
          'Core string functions execution (strlen, strcpy, strcat, strcmp)',
        ],
      ),
    ],
  ),
  PresetCategory(
    name: 'Data Structures',
    color: 0xFFFFE500,
    topics: [
      PresetTopic(
        name: 'Linear Data Structures',
        tasks: [
          'Array element insertion, deletion, and search bounds',
          'Stack implementation using arrays and linked lists',
          'Infix to postfix expression conversion tracking',
          'Postfix expression evaluation via stack',
          'Queue implementation using arrays and circular lists',
          'Double-ended queue (Deque) configurations',
          'Singly, doubly, and circular linked list insertion, deletion, and reversal',
        ],
      ),
      PresetTopic(
        name: 'Non-Linear Data Structures',
        tasks: [
          'Binary tree mathematical properties and nodes calculation',
          'Binary tree preorder, inorder, postorder, and level-order traversals',
          'Binary Search Tree (BST) element insertion, deletion, and search bounds',
          'Max-heap and min-heap array construction and heapify operations',
          'Priority queue extract min and extract max operations via heaps',
          'Graph representation via adjacency matrix and adjacency list',
        ],
      ),
    ],
  ),
  PresetCategory(
    name: 'Algorithms',
    color: 0xFFFF6C00,
    topics: [
      PresetTopic(
        name: 'Complexity Analysis & Searching/Sorting',
        tasks: [
          'Asymptotic notations definition and bounds checking (Big-O, Omega, Theta)',
          'Algorithmic time complexity evaluation',
          'Algorithmic space complexity evaluation',
          'Recurrence relations solving via Master Theorem',
          'Recurrence relations solving via Substitution and Recursion Tree methods',
          'Linear search and binary search execution bounds',
          'Comparison-based sorting algorithms execution (Bubble, Selection, Insertion)',
          'Divide-and-conquer sorting algorithms execution (Merge sort, Quick sort)',
          'Heap sort execution tracking',
          'Linear-time sorting algorithms execution (Counting sort)',
          'Hash functions design and collision resolution (Chaining)',
          'Hash open addressing collision resolution (Linear probing, Quadratic probing, Double hashing)',
        ],
      ),
      PresetTopic(
        name: 'Design Techniques & Graphs',
        tasks: [
          'Greedy paradigm execution (Fractional Knapsack, Job sequencing)',
          'Huffman coding tree generation and bit calculations',
          'Dynamic programming execution (0/1 Knapsack, Longest Common Subsequence)',
          'Dynamic programming matrix sequence optimization (Matrix Chain Multiplication)',
          'Breadth-First Search (BFS) graph execution and tracking',
          'Depth-First Search (DFS) graph execution, time-stamping, and tracking',
          'Topological sorting generation on DAGs',
          'Kruskal’s minimum spanning tree algorithm tracking',
          'Prim’s minimum spanning tree algorithm tracking',
          'Dijkstra’s single-source shortest path algorithm tracing',
          'Bellman-Ford shortest path algorithm tracing',
          'Floyd-Warshall all-pairs shortest path algorithm tracing',
        ],
      ),
    ],
  ),
  PresetCategory(
    name: 'TOC',
    color: 0xFFFF1493,
    topics: [
      PresetTopic(
        name: 'Regular Languages & Finite Automata',
        tasks: [
          'Deterministic Finite Automata (DFA) state design',
          'DFA minimization algorithm execution',
          'Non-deterministic Finite Automata (NFA) state design and NFA to DFA conversion',
          'Regular expression formulation from structural languages',
          'Conversion of Regular expressions to Finite Automata and vice-versa',
          'Regular grammar identification (Left-linear and Right-linear grammars)',
          'Closure properties proof for regular languages',
          'Decision properties verification for regular languages',
          'Pumping lemma execution for non-regular languages proof',
        ],
      ),
      PresetTopic(
        name: 'Context-Free Languages & Pushdown Automata',
        tasks: [
          'Context-Free Grammar (CFG) design for context-free languages',
          'Sentential derivation derivations, parse trees, and ambiguity resolution',
          'Pushdown Automata (PDA) state design (Deterministic and Non-deterministic)',
          'PDA acceptance checking via final state and empty stack configurations',
          'Closure properties proof for context-free languages (CFLs)',
          'Decision properties verification for CFLs',
        ],
      ),
      PresetTopic(
        name: 'Turing Machines & Decidability',
        tasks: [
          'Turing Machine (TM) state design and head transition tracking',
          'Recursive and Recursively Enumerable languages identification',
          'Chomsky Hierarchy grammar classification matching',
          'Decidability properties verification for languages',
          'Halting problem undecidability parsing',
          'Post Correspondence Problem (PCP) undecidability verification',
          'Undecidability proofs execution via language reduction methods',
        ],
      ),
    ],
  ),
  PresetCategory(
    name: 'Compiler Design',
    color: 0xFF2979FF,
    topics: [
      PresetTopic(
        name: 'Lexical and Syntax Analysis',
        tasks: [
          'Lexical analysis tokenization, pattern matching, and lexeme identification',
          'Left recursion removal and left factoring optimization from grammars',
          'LL(1) parsing table construction, First set, and Follow set computations',
          'Operator precedence parsing execution',
          'Shift-Reduce parsing actions tracking (Shift, Reduce, Accept, Error)',
          'LR(0) parsing items generation and parsing table construction',
          'SLR(1) parsing table construction and conflict checking',
          'CLR(1) parsing items generation and parsing table construction',
          'LALR(1) parsing table merging and conflict checking',
        ],
      ),
      PresetTopic(
        name: 'Semantics, Runtime & Intermediate Code',
        tasks: [
          'Syntax-Directed Definitions (SDD) parsing (S-attributed and L-attributed)',
          'Syntax-Directed Translation schemes (SDTS) actions execution',
          'Runtime environment activation records allocation tracing',
          'Intermediate code three-address code generation',
          'Quadruples, triples, and indirect triples intermediate records configuration',
          'Postfix syntax conversions',
        ],
      ),
      PresetTopic(
        name: 'Code Optimization',
        tasks: [
          'Basic blocks partitioning and Control Flow Graph (CFG) construction',
          'Directed Acyclic Graph (DAG) representation of basic blocks',
          'Data flow analysis: Constant propagation execution',
          'Data flow analysis: Liveness analysis execution',
          'Data flow analysis: Common subexpression elimination execution',
          'Loop optimizations implementation (Code motion, Loop unrolling, Loop invariant computations)',
        ],
      ),
    ],
  ),
  PresetCategory(
    name: 'Operating Systems',
    color: 0xFFFF073A,
    topics: [
      PresetTopic(
        name: 'Processes, Threads & IPC',
        tasks: [
          'Process states transitions and Process Control Block (PCB) allocations',
          'System calls tracing and execution mechanics (fork, exec, wait, exit)',
          'User-level threads vs kernel-level threads execution parsing',
          'Inter-process communication implementations (Shared memory, Message passing, Pipes)',
        ],
      ),
      PresetTopic(
        name: 'Concurrency & Synchronization',
        tasks: [
          'Critical section constraints validation (Mutual exclusion, Progress, Bounded waiting)',
          'Software synchronization execution (Peterson\'s solution)',
          'Hardware synchronization primitives execution (TestAndSet, Swap)',
          'Counting and binary semaphores execution and wait/signal tracking',
          'Monitors structural encapsulation synchronization',
          'Bounded-Buffer (Producer-Consumer) synchronization tracking',
          'Readers-Writers synchronization tracking',
          'Dining Philosophers deadlock synchronization tracking',
        ],
      ),
      PresetTopic(
        name: 'Deadlocks',
        tasks: [
          'Deadlock necessary conditions validation (Mutual exclusion, Hold-and-wait, No preemption, Circular wait)',
          'Resource Allocation Graph (RAG) deadlock detection analysis',
          'Deadlock prevention strategies implementation',
          'Banker\'s algorithm safe state and deadlock avoidance validation',
          'Deadlock detection and recovery processes',
        ],
      ),
      PresetTopic(
        name: 'CPU & I/O Scheduling',
        tasks: [
          'CPU scheduling criteria tracking (Turnaround, Waiting, Response, Throughput)',
          'Non-preemptive scheduling tracking (FCFS, SJF, Priority)',
          'Preemptive scheduling tracking (SRTF, Round Robin with time quantum, Preemptive Priority)',
          'Multi-level queue and multi-level feedback queue configurations',
          'Disk scheduling algorithms tracing (FCFS, SSTF, SCAN, C-SCAN, LOOK, C-LOOK)',
        ],
      ),
      PresetTopic(
        name: 'Memory Management & File Systems',
        tasks: [
          'Contiguous memory allocation schemes execution (First-fit, Best-fit, Worst-fit)',
          'Paging framework logical-to-physical address translation tracking',
          'Multi-level page tables address parsing and sizing calculations',
          'Inverted page table structures mapping',
          'Segmentation framework logical-to-physical address translation tracking',
          'Demand paging execution and page fault processing',
          'Page replacement algorithms tracing (FIFO, Optimal, LRU)',
          'Thrashing identification and working set model mechanics',
          'File directory path structural access methods',
          'File storage allocation mapping (Contiguous, Linked, Indexed)',
          'Disk free-space management tracking (Bit vectors, Linked lists)',
        ],
      ),
    ],
  ),
  PresetCategory(
    name: 'Databases',
    color: 0xFF39FF14,
    topics: [
      PresetTopic(
        name: 'Database Design & Relational Model',
        tasks: [
          'ER-model attribute categorization, cardinality constraints, and weak entity keys',
          'ER-diagram to Relational Schema conversion mapping',
          'Relational model domain, key, and referential integrity constraints validation',
          'Functional dependencies inference rules and Armstrong\'s axioms applications',
          'Attribute closure computation from a functional dependency set',
          'Candidate key and super key extraction from schema configurations',
          'Lossless-join decomposition verification matching',
          'Dependency preservation decomposition verification matching',
          'Schema normalization validation (1NF, 2NF, 3NF, BCNF)',
        ],
      ),
      PresetTopic(
        name: 'Query Languages',
        tasks: [
          'Relational algebra operations execution (Select, Project, Cartesian product)',
          'Relational algebra joins execution (Natural join, Theta join, Outer joins)',
          'Tuple and domain relational calculus structural formulations',
          'SQL DDL commands configuration (Create, Alter, Drop, Truncate)',
          'SQL DML basic selection filtering and ordering queries',
          'SQL data aggregations execution (Group By, Having, Count, Sum, Avg)',
          'SQL nested subqueries and set operators execution (Union, Intersect, Except, Exists)',
          'SQL explicit join queries processing',
        ],
      ),
      PresetTopic(
        name: 'Storage, Indexing & Transactions',
        tasks: [
          'File organizations parsing (Sequential, Hash, Heap layout)',
          'Primary, secondary, and clustering indexing structures calculation',
          'B-tree structure node capacity and structural splits calculation',
          'B+ tree structure pointer layouts and path traversals calculation',
          'Transaction ACID properties validations',
          'Transaction execution state transitions tracking',
          'Schedule conflict serializability validation via precedence graphs',
          'Schedule view serializability validation tracking',
          'Schedule recoverability and cascadeless check evaluations',
          'Two-Phase Locking (2PL) protocols tracing (Basic, Strict, Rigorous)',
          'Database deadlock handling, prevention, and timestamping protocols (Wait-Die, Wound-Wait)',
        ],
      ),
    ],
  ),
  PresetCategory(
    name: 'Computer Networks',
    color: 0xFF00F0FF,
    topics: [
      PresetTopic(
        name: 'Network Layering & Switching',
        tasks: [
          'OSI reference model layer-by-layer function matching',
          'TCP/IP protocol stack layer-by-layer function matching',
          'Network switching performance trade-offs (Packet, Circuit, Virtual Circuit switching)',
          'Network delay calculations (Transmission, Propagation, Queuing, Processing delays)',
        ],
      ),
      PresetTopic(
        name: 'Data Link Layer',
        tasks: [
          'Framing mechanics execution (Character count, Character stuffing, Bit stuffing)',
          'Error detection codes calculation (Parity, Checksum)',
          'Cyclic Redundancy Check (CRC) polynomial generation and remainder validation',
          'Hamming distance metric and Hamming error correction codes calculation',
          'Stop-and-Wait flow control efficiency, throughput, and window tracking',
          'Go-Back-N ARQ window tracking and sequence numbering math',
          'Selective Repeat ARQ window tracking and sequence numbering math',
          'Pure ALOHA and Slotted ALOHA network throughput calculations',
          'CSMA/CD protocol collision tracking, back-off timer math, and minimum frame length equations',
          'CSMA/CA wireless collision avoidance tracking',
          'Ethernet IEEE 802.3 frame structure parsing',
          'Hardware interconnect network bridging, switching logic, and transparent loop resolutions',
        ],
      ),
      PresetTopic(
        name: 'Network Layer',
        tasks: [
          'IPv4 classful addressing ranges and network/host boundaries split',
          'IPv4 subnetting configuration and mask computations',
          'CIDR notation address prefix routing allocation and supernetting',
          'IPv4 packet header field parsing (Header length, Total length, TTL, Protocol)',
          'IP fragmentation packet off-sets and flag indicators calculations',
          'Distance Vector Routing protocol iterations and Count-to-Infinity errors tracking',
          'Link State Routing protocol Dijkstra link database convergence tracking',
          'Border Gateway Protocol (BGP) path-vector path selection basic concepts',
          'Address Resolution Protocol (ARP) frame request and reply translation mapping',
          'Dynamic Host Configuration Protocol (DHCP) allocation steps tracking',
          'Internet Control Message Protocol (ICMP) error status query handling',
          'Network Address Translation (NAT) address translation tracking (Static, Dynamic, PAT)',
          'IPv6 basic header address enhancements tracking',
        ],
      ),
      PresetTopic(
        name: 'Transport & Application Layer',
        tasks: [
          'Transport layer port multiplexing and demultiplexing processes',
          'UDP protocol header checksum and datagram format parsing',
          'TCP protocol header fields parsing (Sequence number, Acknowledgment number, Flags)',
          'TCP 3-way handshake connection establishment tracking',
          'TCP connection termination steps tracking',
          'TCP sliding window flow control window sizing execution',
          'TCP congestion control phases tracking (Slow start, Congestion avoidance)',
          'TCP congestion control timeout reactions tracking (Fast retransmit, Fast recovery)',
          'Socket programming basic syscalls sequencing (socket, bind, listen, accept, connect)',
          'Domain Name System (DNS) recursive and iterative query resolution tracking',
          'SMTP, POP3, and IMAP electronic mail transactions protocol steps',
          'HTTP and HTTPS stateless transactions, request/response headers parsing',
          'FTP control and data connection state tracking',
          'SSH secure remote terminal session mechanics',
        ],
      ),
    ],
  ),
  PresetCategory(
    name: 'General Aptitude',
    color: 0xFFD500F9,
    topics: [
      PresetTopic(
        name: 'Verbal & Analytical Aptitude',
        tasks: [
          'Basic English grammar parts of speech validation (Tenses, Articles, Prepositions)',
          'English grammar syntax checks (Conjunctions, Verb-noun agreement)',
          'Vocabulary synonym and antonym context completions',
          'Reading comprehension textual critical conclusions extraction',
          'Narrative sequencing line rearrangements',
          'Deductive logic syllogisms mapping',
          'Inductive logic pattern string sequence extensions',
          'Verbal analogy word pairing matches',
          'Analytical puzzles, blood relations, and seating arrangement tracking',
        ],
      ),
      PresetTopic(
        name: 'Quantitative Aptitude',
        tasks: [
          'Data interpretation bar graphs, line plots, and tables metric computations',
          'Data interpretation pie charts percentage angle shares calculations',
          'Numerical ratio and proportion scaling computations',
          'Profit, loss, and percentage margin operations',
          'Simple and compound interest time-growth computations',
          'Exponents, logs, surds, and algebraic index variations solving',
          'Permutations and combinations fundamental arrangement counts',
          'Mensuration area calculations for 2D geometric polygons',
          'Mensuration volume calculations for 3D geometric shapes',
          'Coordinate geometry slopes, distances, midpoints, and linear equations intersections',
          'Elementary data sets mean, median, mode, and sample variance evaluations',
          'Speed, time, and distance equations (Relative speed, trains, upstream/downstream boats)',
          'Work, time, and team resource efficiency balances',
        ],
      ),
      PresetTopic(
        name: 'Spatial Aptitude',
        tasks: [
          '2D pattern assembly fragmentation compilations',
          '3D pattern assembly block construction views matching',
          'Spatial translation and scaling visual tracking',
          'Spatial coordinate rotation and mirror image generation matching',
          'Paper folding step trajectories path matching',
          'Paper cutting symmetric internal punch patterns tracing',
          '3D solid cube orientations tracking',
        ],
      ),
    ],
  ),
];
