// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkJYXU83j_3Wfr0JSY6bo_p1A7-jlwaxw',
    appId: '1:981770496770:web:eafda970bce41b91de701b',
    messagingSenderId: '981770496770',
    projectId: 'gateletics',
    authDomain: 'gateletics.firebaseapp.com',
    storageBucket: 'gateletics.firebasestorage.app',
    measurementId: 'G-FCM284GY0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD9GEpkoqirkyZjOJ6FD5rcgvQhYfoBic',
    appId: '1:981770496770:android:bf38f16f882e62fade701b',
    messagingSenderId: '981770496770',
    projectId: 'gateletics',
    storageBucket: 'gateletics.firebasestorage.app',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkJYXU83j_3Wfr0JSY6bo_p1A7-jlwaxw',
    appId: '1:981770496770:web:9fb048c67da5202ede701b',
    messagingSenderId: '981770496770',
    projectId: 'gateletics',
    authDomain: 'gateletics.firebaseapp.com',
    storageBucket: 'gateletics.firebasestorage.app',
    measurementId: 'G-TP91P3ND2V',
  );
}
